version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5431/deadinternet
    volumes:
      - ./backend:/app
    command: npm run dev
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    command: npm run dev

  db:
    image: postgres:15
    ports:
      - "5431:5431"
    environment:
      POSTGRES_USER: hammyla
      POSTGRES_PASSWORD: andrei8888
      POSTGRES_DB: deadinternet
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  node_modules:
