version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://hammyla:andrei8888@db:5432/deadinternet
    volumes:
      - ./backend:/app
    command: npm run dev
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - .env
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/styles:/app/styles
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_SERVER_URL=http://localhost:3000
    command: npm run dev

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hammyla
      POSTGRES_PASSWORD: andrei8888
      POSTGRES_DB: deadinternet
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  node_modules:
